name: Publish Application on GitHub Pages
# Don't add something here until the plugin is available on Maven, the CI is quite long :(
on: [workflow_dispatch]
jobs:
  # Build job
  build:
    name: Build Kotlin/Wasm Stories
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish local Storytale plugin
        run: ./gradlew publishToMavenLocal

      - name: Run Gradle Tasks
        run: |
          cd examples
          ../gradlew wasmJsBrowserStoriesProductionExecutableDistribution

      - name: Fix permissions
        run: |
          chmod -v -R +rX "examples/build/dist/wasmJs/StoriesProductionExecutable/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: examples/build/dist/wasmJs/StoriesProductionExecutable

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4